Markdown: Step 7.1. The previous step failed, and required updating to gatsby@latest
Error:
`error getNodesByType is not a function`

Resolved by:
`npm i gatsby@latest`